version: '3.7'
services:
  mongodb-primary:
    container_name: mongoDBElectionsApp
    image: docker.io/bitnami/mongodb:4.4-debian-10
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      # - MONGODB_REPLICA_SET_MODE=primary
      # - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ROOT_PASSWORD=dbpwd
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=dbpwd
      - MONGODB_DATABASE=golang
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - mongodb_data_container:/bitnami/mongodb
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongoDBElectionsApp
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: dbpwd
    depends_on:
      - mongodb-primary
    links:
      - mongodb-primary
    networks:
      - mongo-compose-network
volumes:
  mongodb_data_container:
    driver: local
networks:
  mongo-compose-network:
    driver: bridge
