// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package repository

import mock "github.com/stretchr/testify/mock"

// Connection is an autogenerated mock type for the Connection type
type Connection struct {
	mock.Mock
}

// SetupIndexes provides a mock function with given fields:
func (_m *Connection) SetupIndexes() {
	_m.Called()
}
