// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package repository

import mock "github.com/stretchr/testify/mock"

// Steps is an autogenerated mock type for the Steps type
type Steps struct {
	mock.Mock
}

// SetupIndexes provides a mock function with given fields:
func (_m *Steps) SetupIndexes() {
	_m.Called()
}
